#!/usr/bin/env python3
"""Block committed reports that mention locked OOS dates."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from core.data_lockup import current_lockup, report_mentions_locked_date  # noqa: E402


def _staged_report_files() -> list[Path]:
    completed = subprocess.run(
        ["git", "diff", "--cached", "--name-only", "--diff-filter=ACMRT"],
        cwd=ROOT,
        check=False,
        text=True,
        capture_output=True,
    )
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr.strip() or "git diff failed")
    paths = []
    for raw in completed.stdout.splitlines():
        path = Path(raw)
        if path.parts and path.parts[0] == "reports":
            paths.append(ROOT / path)
    return paths


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--allow-oos-validation-report",
        action="store_true",
        help="Permit reports generated by the explicit OOS validation workflow.",
    )
    parser.add_argument("files", nargs="*", help="Files to inspect; defaults to staged reports.")
    args = parser.parse_args(argv)

    lockup = current_lockup()
    if lockup is None:
        return 0

    files = [Path(path) for path in args.files] if args.files else _staged_report_files()
    failures = []
    for file_path in files:
        if not file_path.exists() or file_path.is_dir():
            continue
        text = file_path.read_text(encoding="utf-8", errors="ignore")
        if args.allow_oos_validation_report and "OOS validation" in text:
            continue
        if report_mentions_locked_date(text):
            failures.append(file_path)

    if failures:
        print(
            "OOS lockup leakage detected for "
            f"{lockup.start_date.isoformat()}..{lockup.end_date.isoformat()}:",
            file=sys.stderr,
        )
        for file_path in failures:
            try:
                label = file_path.relative_to(ROOT)
            except ValueError:
                label = file_path
            print(f"  {label}", file=sys.stderr)
        print(
            "Use scheduler/run_backtest.py --oos-validation for the single-use "
            "validation workflow, or remove locked-window references.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
